### ISSUE TITLE
Unable to Read Spark Parquet Schema DECIMAL()

### ISSUE THREAD

**Issue by hhoughgg** [fraugster/parquet-go#62] opened 2022-01-12 00:28 UTC
Library reads the schema def as below and the panics on conversion to schema elements

message spark_schema {
  optional int32 event_date (DATE);
  optional int96 datetime;
  optional fixed_len_byte_array(9) id1 (DECIMAL);
  optional fixed_len_byte_array(9) id2 (DECIMAL);
  optional fixed_len_byte_array(9) id3 (DECIMAL);
  optional binary name (UTF8);
}

`panic: line 4: expected (, got ")" instead`

Looks like its failing since the decimal precision and scale is not specified in the schema. Spark 2.4 produced this file and has no trouble reading it. I have also used other schema readers and it spits out (DECIMAL(20,0)) as the schema instead. I am not sure if this is some default if you fail to specify? Seems that it is valid not to specify?

I have also been having trouble writing decimal schema for spark to read as it seems to fail to recognize that the field is a decimal and instead interprets the type as just fixed length byte array. For the low level writer what is the correct way write a decimal into a byte array?

Everything else is working for me just cannot seem to read or write decimal types in regard to spark.

Thanks

**Comment by akrennmair** [comment] 2022-01-30 20:53
This will be fixed in the next release. Same issue as #12.

**Comment by bluestreek18** [comment] 2022-01-31 18:54
@akrennmair will this also fix the issue with not being able to write decimals with this library? This fixes reading the schema from spark but if I write a file and try to read with spark it fails.

**Comment by akrennmair** [comment] 2022-02-01 12:06
@bluestreek18 what's spark's specific error message? Do you have a way for me to reproduce this?

**Comment by bluestreek18** [comment] 2022-02-01 20:40
org.apache.spark.sql.AnalysisException: Illegal Parquet type: FIXED_LEN_BYTE_ARRAY;

If it set metadata to tell spark its a decimal type instead of FIXED_LEN_BYTE_ARRAY I get a new error message but still no luck. I was able to get it to work fine with with the other go parquet lib and I tried using their StrIntToByteArray function with no luck.

`package main

import (
	"log"
	"os"

	goparquet "github.com/fraugster/parquet-go"
	"github.com/fraugster/parquet-go/parquet"
	"github.com/fraugster/parquet-go/parquetschema"
)

func main() {
	f, err := os.OpenFile("output.parquet", os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0644)
	if err != nil {
		log.Fatalf("Opening output file failed: %v", err)
	}
	defer f.Close()

	schemaDef, err := parquetschema.ParseSchemaDefinition(
		`message spark_schema {
			required binary name (STRING);
			optional fixed_len_byte_array(9) id (DECIMAL(20,0));
			optional double score;
		}`)
	if err != nil {
		log.Fatalf("Parsing schema definition failed: %v", err)
	}

	fw := goparquet.NewFileWriter(f,
		goparquet.WithCompressionCodec(parquet.CompressionCodec_SNAPPY),
		goparquet.WithSchemaDefinition(schemaDef),
		goparquet.WithCreator("write-lowlevel"),
	)

	inputData := []struct {
		Name  string
		ID    []byte
		Score float64
	}{
		{Name: "jimmy", ID: []byte{0, 1, 2, 3, 4, 5, 6, 7, 8}, Score: 284928.83},
		{Name: "jonny", ID: []byte{0, 1, 2, 3, 4, 5, 6, 7, 8}, Score: 98},
		{Name: "jimmyjohns", ID: []byte{0, 1, 2, 3, 4, 5, 6, 7, 8}, Score: 8232.82},
		{Name: "jimjonjonny", ID: []byte{0, 1, 2, 3, 4, 5, 6, 7, 8}, Score: 1329.11},
		{Name: "j", ID: []byte{0, 1, 2, 3, 4, 5, 6, 7, 8}, Score: 4224.11},
	}

	for _, input := range inputData {
		if err := fw.AddData(map[string]interface{}{
			"name":  []byte(input.Name),
			"id":    input.ID,
			"score": input.Score,
		}); err != nil {
			log.Fatalf("Failed to add input %v to parquet file: %v", input, err)
		}
	}

	if err := fw.Close(); err != nil {
		log.Fatalf("Closing parquet file writer failed: %v", err)
	}
}
`

**Comment by akrennmair** [comment] 2022-02-02 12:25
@bluestreek18 thanks for the example! I tried to reproduce the issue with pyspark, and I got this:

```
>>> foo = spark.read.parquet("output.parquet")
>>> foo.createOrReplaceTempView("output")
>>> result = spark.sql("SELECT * FROM output")
>>> result.show()
+-----------+-----------------+---------+
|       name|               id|    score|
+-----------+-----------------+---------+
|      jimmy|72623859790382856|284928.83|
|      jonny|72623859790382856|     98.0|
| jimmyjohns|72623859790382856|  8232.82|
|jimjonjonny|72623859790382856|  1329.11|
|          j|72623859790382856|  4224.11|
+-----------+-----------------+---------+

>>> 
```
To me that looks like nothing is obviously wrong. I experimented with just `(DECIMAL)` as converted type for the `id` column, either generating a default logical type or not generating a logical type at all, but this either produces parquet files that the Java implementation can't seem to parse, or they work equally well as the example above.

**Comment by bluestreek18** [comment] 2022-02-20 20:55
I'm still getting the same error using Spark 2.4.8 - which version of spark did you test with?

**Comment by bluestreek18** [comment] 2022-03-13 00:30
I was able to fix this by adding the code below after declaring filewriter. Seems like older implementations of parquet require the converted type to be set for decimal or it will only see the fields underlying type.

`for _, v := range fw.Columns() {
		var ct parquet.ConvertedType = 5
		ele := v.Element()
		if ele.Name == "id" {
			log.Println("Setting id converted type to decimal")
			ele.ConvertedType = &ct
		}
	}
`

**Closed** 2022-03-28 21:14 UTC

**Comment by hhoughgg** [comment] 2022-04-07 19:27
@akrennmair is it worth a pr that changes the schema to automatically set converted type for decimals at least for data page v1 which is more likely to require these settings that are deprecated from newer versions of parquet?
